config/routes.rb
Unified::Application.routes.draw do

  resources :documents

  resources :promotions

  resources :promotion_payment_statuses

  resources :promotion_categories

  resources :events

  resources :gallery_images

  resources :galleries do
    resources :gallery_images
  end

  root 'spree/home#index'

  resources :team_members

  resources :categories

  resources :documents

  devise_for :users

  devise_for :customers, :controllers => {:registrations => "customers/registrations", :sessions => 'customers/sessions'}
  devise_for :assistants, :controllers => {:sessions => 'assistants/sessions'}
  
  
  mount Spree::Core::Engine, :at => '/shop'

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  comfy_route :cms_admin, :path => '/cms-admin'

  comfy_route :cms, :path => '/cms', :sitemap => false

  get '/list_of_orders' => 'manage_orders#list_of_orders'
  get '/party_name' => 'manage_orders#party_name'
  get '/show_material_description' => 'manage_orders#show_material_description'
  put '/update_order_status/:id' => 'manage_orders#update_order_status'
  resources :posts
  resources :manage_orders
  
  Spree::Core::Engine.routes.prepend do
    resources :taxons
  end

  

end

app/views/shared/_footer.html.erb
<div class="background" id="footer_red_background">
  <div class="background" id="footer_glow_background">
         <footer>
            <div class = "footer_left"><strong>Please drink responsibly</strong></div>
            <div class = "footer_right"> Copyright Angostura &reg;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;Developed by <a href="http://monstermediagroup.com" target="_blank"><img src="/images/monster-logo.png" alt="Monster Media Group" title="Monster Media Group" /></a></div>
            <div class="clear"><!-- --></div>
         </footer>
         
  </div>
</div>  

app/views/shared/_head.html.erb
<meta charset="utf-8">
<title>Angostura Extranet</title>
<meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
<meta content="width=device-width, initial-scale=1.0, maximum-scale=1" name="viewport">
<%= canonical_tag %>
<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>
<%= javascript_include_tag src='https://www.google.com/jsapi' %>
<%= javascript_include_tag "application", "store/all", "data-turbolinks-track" => true %>
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6/html5shiv.min.js"></script>
<![endif]-->
<%= yield :head %>

app/views/shared/_header.html.erb
     <div class="background" id="header_background">
        	<header class="header">
        		<div class="float_left">
                    <a href="/" class="float_left logo"><img class="float_left" src="/images/logo.png"></a>
                	<span class="float_left header_item tagline">Please Enjoy Responsibly</span>
                </div>
                <div class="float_right">                    
                       <% if user_signed_in? %>
                          <div style = "float: left; padding: 15px 0 0 0;" >
			  <%= render :partial => 'spree/shared/search' %>
			  </div>
	               <% end %>
                    <ul class="float_left header_item topnav_ul">
                        <% if user_signed_in? %>
                             <li><%= link_to "Shopping Cart", "/shop/cart" %></li>
                             <% if defined? destroy_user_session_path %>
                                     <li><%= link_to "My Profile", "/users/edit" %></li>
                                     <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
                             <% else %>
                                     <li><%= link_to "My Profile", "/users/edit" %></li>
                                     <li><%= link_to "Logout", "/users/sign_out", :method => :delete %></li>
                             <% end %>
                             
                        <% elsif customer_signed_in? %>
                          <li><%= link_to "Shopping Cart", "/shop/cart" %></li>
                          <% if defined? destroy_customer_session_path %>
                              <li><%= link_to "My Profile", "/customers/edit" %></li>
                              <li><%= link_to "Logout", destroy_customer_session_path, :method => :delete %></li>
                          <% else %>
                              <li><%= link_to "My Profile", "/customers/edit" %></li>
                              <li><%= link_to "Logout", "/customers/sign_out", :method => :delete %></li>
                          <% end %>
                        <% elsif assistant_signed_in? %>
                          <li><%= link_to "Shopping Cart", "/shop/cart" %></li>
                          <% if defined? destroy_assistant_session_path %>
                              <li><%= link_to "My Profile", "/assistants/edit" %></li>
                              <li><%= link_to "Logout", destroy_assistant_session_path, :method => :delete %></li>
                          <% else %>
                              <li><%= link_to "My Profile", "/assistants/edit" %></li>
                              <li><%= link_to "Logout", "/assistants/sign_out", :method => :delete %></li>
                          <% end %>

                        <% else  %>
                          <li><%= link_to "Log In", "/users/sign_in" %></li>
                          <li><%= link_to "Customer Log In", "/customers/sign_in" %></li>
                          <li><%= link_to "Assistant Log In", "/assistants/sign_in" %></li>
                        <% end %>
                    </ul>
                </div>
                <div class="clear"><!-- --></div>
    		</header> 
        </div><!-- #header_background -->
        
        <div class="background" id="navigation_red_background">
        <div class="background" id="navigation_glow_background">
            <nav class="navigation">
            	<ul class="float_left main_menu">
                    <!-- 
                 --><li>BRANDS
                        <ul class="sub_menu">
                            <li><a href="/categories/3">Brand Education</a></li>
                            <li><a href="/categories/2">Brand Guidelines</a></li>
                            <li><a href="/categories/12">Brand History</a></li>
                            <li><a href="/team_members">Brand Team</a></li>
                        </ul>
                    </li><!-- 
                 --><li>PRODUCTS
                        <ul class="sub_menu">
                            <li><a href="/shop/taxons">Product Range</a></li>
                            <li><a href="/categories/10">Production Techniques</a></li>
                            <li><a href="/categories/11">Technical Specs</a></li>
                        </ul>
                    </li><!-- 
                 --><li>RESOURCES
                        <ul class="sub_menu">
                            <li><a href="/categories/4">Downloads</a></li>
                            <li><a href="/categories/5">On trade promos</a></li>
                            <li><a href="/categories/6">Off trade promos</a></li>
                            <li><a href="/categories/7">Press Releases</a></li>
                            <li><a href="/categories/8">Presentations</a></li>
                            <li><a href="/categories/9">Toolkits</a></li>
                            <li><a href="/categories/13">Logos</a></li>                       
                        </ul>
                    </li><!-- 
                 --><li>EVENTS
                        <ul class="sub_menu">
                            <li><a href="/events">Events Diary</a></li>
                            <li><a href="/galleries">Events Gallery</a></li>
                        </ul>
                    </li><!-- 
                 --><li><a href="/shop/products">POS &amp; MERCHANDISE</a></li><!-- 
                 --><li>
                        ORDERS
                        <ul class="sub_menu">
                          <% if customer_signed_in?  %>
                              <li><a href="/manage_orders">Create Sales Order</a></li>
                          <% end  %>
                          <% if assistant_signed_in? || customer_signed_in?  %>
                              <%# if current_customer.is_admin  %>
                              <li><a href="/list_of_orders">List of orders</a></li>
                              <%# end %>
                          <% end %>
                        </ul>
                    </li><!--
                 -->
					<li>
						AGCC 2016
						<ul class="sub_menu">
							<li><a href="/categories/20">Promo Videos</a></li>
							<li><a href="/categories/21">AGCC Guidelines</a></li>
						</ul>
					</li>
					<!--
                 -->
					<li>
						NO. 1 CASK COLLECTION
						<ul class="sub_menu">
							<li><a href="/categories/23">Market Launch Manual</a></li>
							<li><a href="/categories/24">Photos</a></li>
							<li><a href="/categories/25">Fact Sheet</a></li>
							<li><a href="/categories/26">Brochure &amp; Mini Booklet</a></li>
							<li><a href="/categories/27">Press Release</a></li>
							<li><a href="/categories/28">Q&amp;A</a></li>
						</ul>
					</li>
                </ul>
                <div class="clear"><!-- --></div>
            </nav>
        </div><!-- #navigation_red_background -->    
        </div><!-- #navigation_glow_background -->

app/views/shared/_search.html.erb
<% @taxons = @taxon && @taxon.parent ? @taxon.parent.children : Spree::Taxon.roots %>
<%= form_tag spree.products_path, :method => :get do %>
  <%= search_field_tag :keywords, params[:keywords], :placeholder => Spree.t(:search) %>
<% end %>