config/routes.rb
Unified::Application.routes.draw do

  resources :documents

  resources :promotions

  resources :promotion_payment_statuses

  resources :promotion_categories

  resources :events

  resources :gallery_images

  resources :galleries do
    resources :gallery_images
  end

  root 'spree/home#index'

  resources :team_members

  resources :categories

  resources :documents

  devise_for :users

  devise_for :customers, :controllers => {:registrations => "customers/registrations", :sessions => 'customers/sessions'}
  devise_for :assistants, :controllers => {:sessions => 'assistants/sessions'}
  
  
  mount Spree::Core::Engine, :at => '/shop'

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  comfy_route :cms_admin, :path => '/cms-admin'

  comfy_route :cms, :path => '/cms', :sitemap => false

  get '/list_of_orders' => 'manage_orders#list_of_orders'
  get '/party_name' => 'manage_orders#party_name'
  get '/show_material_description' => 'manage_orders#show_material_description'
  put '/update_order_status/:id' => 'manage_orders#update_order_status'
  resources :posts
  resources :manage_orders
  
  Spree::Core::Engine.routes.prepend do
    resources :taxons
  end

  

end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :promotion
  mount_uploader :file, DocumentUploader
end

app/controllers/documents_controller.rb
class DocumentsController < InheritedResources::Base

before_action :set_document, only: [:show, :edit, :update, :destroy]

  
  def create
    @document = Document.new(document_params)
    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render action: 'show', status: :created, location: @document }
      else
        format.html { render action: 'new' }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Promotion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end
  
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    def document_params
      params.require(:document).permit(:title, :document_id, :file)
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.haml
= form_for @document do |f|
  - if @document.errors.any?
    #error_explanation
      %h2= "#{pluralize(@document.errors.count, "error")} prohibited this document from being saved:"
      %ul
        - @document.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :file
    %span{:class => "input_wrapper"}
      = f.file_field :file
  .actions
    = f.submit 'Save'

app/views/documents/edit.html.haml
%h1 Editing document

= render 'form'

= link_to 'Show', @document
\|
= link_to 'Back', documents_path

app/views/documents/index.html.haml
%h1 Listing documents

%table
  %tr
    %th Title
    %th File
    %th
    %th
    %th

  - @documents.each do |document|
    %tr
      %td= document.title
      %td= document.file
      %td= link_to 'Show', document
      %td= link_to 'Edit', edit_document_path(document)
      %td= link_to 'Destroy', document, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Document', new_document_path

app/views/documents/new.html.haml
%h1 New document

= render 'form'

= link_to 'Back', documents_path

app/views/documents/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @document.title
%p
  %b File:
  = @document.file

= link_to 'Edit', edit_document_path(@document)
\|
= link_to 'Back', documents_path