config/routes.rb
Unified::Application.routes.draw do

  resources :documents

  resources :promotions

  resources :promotion_payment_statuses

  resources :promotion_categories

  resources :events

  resources :gallery_images

  resources :galleries do
    resources :gallery_images
  end

  root 'spree/home#index'

  resources :team_members

  resources :categories

  resources :documents

  devise_for :users

  devise_for :customers, :controllers => {:registrations => "customers/registrations", :sessions => 'customers/sessions'}
  devise_for :assistants, :controllers => {:sessions => 'assistants/sessions'}
  
  
  mount Spree::Core::Engine, :at => '/shop'

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  comfy_route :cms_admin, :path => '/cms-admin'

  comfy_route :cms, :path => '/cms', :sitemap => false

  get '/list_of_orders' => 'manage_orders#list_of_orders'
  get '/party_name' => 'manage_orders#party_name'
  get '/show_material_description' => 'manage_orders#show_material_description'
  put '/update_order_status/:id' => 'manage_orders#update_order_status'
  resources :posts
  resources :manage_orders
  
  Spree::Core::Engine.routes.prepend do
    resources :taxons
  end

  

end

app/models/gallery_image.rb
class GalleryImage < ActiveRecord::Base
  belongs_to :gallery
  mount_uploader :image, ImageUploader
end

app/controllers/gallery_images_controller.rb
class GalleryImagesController < InheritedResources::Base

  before_action :set_gallery_image, only: [:show, :edit, :update, :destroy]
  
  def index
     @gallery = Gallery.find(params[:gallery_id])
     @gallery_images = @gallery.gallery_images.page(params[:page]).per(2)
  end

  def create
    @gallery_image = GalleryImage.new(gallery_image_params)
    #@gallery_image.gallery = Gallery.find(params[:gallery_id])
    respond_to do |format|
      if @gallery_image.save
        format.html { redirect_to @gallery_image, notice: 'Gallery Image was successfully added.' }
        format.json { render action: 'show', status: :created, location: @gallery_image }
      else
        format.html { render action: 'new' }
        format.json { render json: @gallery_image.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    
    respond_to do |format|
      if @gallery_image.update(gallery_image_params)
        format.html { redirect_to @gallery_image, notice: 'Gallery Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gallery_image.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def show
      render :layout => "display"
  end 
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery_image
      @gallery_image = GalleryImage.find(params[:id])
    end
  
    def gallery_image_params
      params.require(:gallery_image).permit(:title, :gallery_id, :image, :description, :text)
    end
end

app/helpers/gallery_images_helper.rb
module GalleryImagesHelper
end

app/views/gallery_images/_form.html.haml
- if params[:gallery_id].nil? 
  - gallery = @gallery_image.gallery
- else 
  - gallery = Gallery.find(params[:gallery_id])

= form_for @gallery_image, :html => {:multipart => true} do |f|
  - if @gallery_image.errors.any?
    #error_explanation
      %h2= "#{pluralize(@gallery_image.errors.count, "error")} prohibited this gallery_image from being saved:"
      %ul
        - @gallery_image.errors.full_messages.each do |msg|
          %li= msg
 
  = f.hidden_field :gallery_id, :value => params[:gallery_id]
  .field
    = f.label :title
    %span{:class => "input_wrapper"}
      = f.text_field :title
  .field
    = f.label :description
    %span{:class => "input_wrapper"}
      = f.text_area :description
  .field
    = f.label :image
    %span{:class => "input_wrapper"}
      = f.file_field :image
  .field
    = f.label :text
    %span{:class => "input_wrapper"}
      = f.text_area :text
  .actions
    %span{:class => "btn_wrapper"}
      = f.submit 'Save'

app/views/gallery_images/edit.html.haml
%h1 
  Editing "
  = @gallery_image.title
  "

= render 'form'

= link_to 'Show', @gallery_image

= link_to 'Back', gallery_images_path

app/views/gallery_images/index.html.haml
- gallery = Gallery.find(params[:gallery_id])
%section{:class => "float_left content_full"}

  #image_view{:style => "display:none;" }
    %iframe{:id => "image_frame", :src => "", :width => 700, :height => 900, :scrolling => "no" }

  %h1= gallery.title
  - if can? :update, gallery
    = link_to 'New Gallery image', new_gallery_gallery_image_path(gallery)
    = " | "
    = link_to 'Edit Gallery', edit_gallery_path(gallery)
  %p= gallery.text
  
  - paginate @gallery_images

  %div{:class => "float_left fifth product_bounds"}

    - @gallery_images.each do |gallery_image|
      %div{:class => "float_left fifth product_fifth"}
        = link_to (image_tag gallery_image.image_url(:thumb)), gallery_image_path(gallery_image), :class => "gallery_image"
        %br
        %h2= link_to gallery_image.title, gallery_image_path(gallery_image), :class => "gallery_image_name"
        - if can? :update, gallery
          = link_to 'Edit', edit_gallery_image_path(gallery_image), :class => "gallery_image_name"
        - if can? :destroy, gallery
          = link_to 'Destroy', gallery_image, :class => "product_name", :method => :delete, :data => { :confirm => 'Are you sure?' }
    

app/views/gallery_images/new.html.haml
- gallery = Gallery.find(params[:gallery_id])

%h1
  New Gallery Image For "
  = gallery.title
  "

= render 'form'

= link_to 'Back', gallery_gallery_images_path(gallery)

app/views/gallery_images/show.html.haml
%h1
  = @gallery_image.title

%p
  %strong Gallery:
  = Gallery.find(@gallery_image.gallery).title
= image_tag @gallery_image.image_url(), :class =>"event_image"
%p
  = @gallery_image.text

- if can? :update, @gallery_image.gallery
  =# link_to 'Edit', edit_gallery_gallery_image_path(@gallery_image.gallery, @gallery_image)
  
=# link_to 'Back', gallery_gallery_images_path(@gallery_image.gallery)