config/routes.rb
Unified::Application.routes.draw do

  resources :documents

  resources :promotions

  resources :promotion_payment_statuses

  resources :promotion_categories

  resources :events

  resources :gallery_images

  resources :galleries do
    resources :gallery_images
  end

  root 'spree/home#index'

  resources :team_members

  resources :categories

  resources :documents

  devise_for :users

  devise_for :customers, :controllers => {:registrations => "customers/registrations", :sessions => 'customers/sessions'}
  devise_for :assistants, :controllers => {:sessions => 'assistants/sessions'}
  
  
  mount Spree::Core::Engine, :at => '/shop'

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  comfy_route :cms_admin, :path => '/cms-admin'

  comfy_route :cms, :path => '/cms', :sitemap => false

  get '/list_of_orders' => 'manage_orders#list_of_orders'
  get '/party_name' => 'manage_orders#party_name'
  get '/show_material_description' => 'manage_orders#show_material_description'
  put '/update_order_status/:id' => 'manage_orders#update_order_status'
  resources :posts
  resources :manage_orders
  
  Spree::Core::Engine.routes.prepend do
    resources :taxons
  end

  

end

app/models/category.rb
class Category < ActiveRecord::Base
     has_many :posts
     mount_uploader :image, ImageUploader   
end

app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :text
    = f.text_area :text
  .actions
    = f.submit 'Save'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
%h1 Listing categories

%table
  %tr
    %th Title
    %th Description
    %th Text
    %th
    %th
    %th

  - @categories.each do |category|
    %tr
      %td= category.title
      %td= category.description
      %td= category.text
      %td= link_to 'Show', category
      %td= link_to 'Edit', edit_category_path(category)
      %td= link_to 'Destroy', category, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Category', new_category_path

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
= link_to @category.title + " > ", category_path(@category)
%br
%br
%h1= @category.title
- if (!@category.image_url().nil? & !@category.text.nil?)
  %div{:class => "category_header"}
    - if !@category.image_url().nil?
      = image_tag(@category.image_url(:thumb).to_s, :class => "post_image")
    %p= @category.text.html_safe
    %div{:class => "clear"} <!-- -->
%ul{:class => "category_posts_list"}
  - if params[:taxonomy].nil?
    - posts = @category.posts
  - else
    - taxonomy = params[:taxonomy]
    - posts = Post.where(category: @category, product_range_id: taxonomy)
  - counter = 1 
  - posts.each do | post |
    - if ProductRangesUser.where(:user_id => current_user, :taxonomy_id => post.product_range).count > 0
       
      %li>
        %div{:class => "category_posts_item"}
          %h2{:class => "category_posts_header"}= post.title
          %div{:class => "category_post_image"}
            = link_to image_tag(post.image_url(:thumb).to_s, :class => "category_posts_images"), post_path(post)
            %div{:class => "clear"} <!-- -->
          - if !post.product_range.nil?
            %p{:align => "justify"}
              %strong Product Range: 
              = post.product_range.name
              
          = simple_format post.description
          %p{:style => "text-align:right"}
            %strong
              = link_to("More", post_path(post) )
          %div{:class => "clear"} <!-- -->
      /      
      - if counter % 3 == 0
        %li{:class => "clear"}>
          /
        /
      - counter += 1       